/*
 * quhit_substrate.c — Substrate Opcode Implementations
 *
 * 18 quantum gates derived from cross-probe side-channel analysis
 * of the physical substrate. Each hex pattern → a concrete operation
 * on the D=6 quhit state space.
 *
 * Generated by universe_sidechannel.c, implemented here.
 */

#include "quhit_engine.h"
#include "substrate_opcodes.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

/* ═══════════════════════════════════════════════════════════════════════════════
 * SUBSTRATE CONSTANTS — from the probe
 * ═══════════════════════════════════════════════════════════════════════════════ */

#define PHI         1.6180339887498949   /* Golden ratio                     */
#define PHI_INV     0.6180339887498948   /* 1/φ                              */
#define DOTTIE      0.7390851332151607   /* Dottie number = fixed point cos  */
#define SQRT2_CONST 1.4142135623730949   /* √2 from substrate FPU attractor  */
#define SUB_D       6                    /* HexState dimension               */
#define SUB_D2      36                   /* Joint state dimension            */

/* Omega for D=6: ω = e^(2πi/6) */
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ═══════════════════════════════════════════════════════════════════════════════
 * HELPER — get state pointer safely
 * ═══════════════════════════════════════════════════════════════════════════════ */

static inline QuhitState* sub_get_state(QuhitEngine *eng, uint32_t id)
{
    if (id >= eng->num_quhits) return NULL;
    return &eng->quhits[id].state;
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x00: SUB_NULL — Project to vacuum |0⟩
 *
 * The most common substrate opcode (33 cross-probe hits).
 * Everything decays to ground state. The universe's default instruction.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_null(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;
    memset(s, 0, sizeof(*s));
    s->re[0] = 1.0;
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x0000: SUB_VOID — Annihilate all amplitude
 *
 * Total erasure. The state becomes the zero vector.
 * Not unitary — this is a measurement back-action / decoherence event.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_void(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Kill local state */
    memset(s, 0, sizeof(*s));

    /* If entangled, kill the joint state too */
    Quhit *q = &eng->quhits[id];
    if (q->pair_id >= 0) {
        QuhitPair *p = &eng->pairs[q->pair_id];
        memset(&p->joint, 0, sizeof(p->joint));
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x40: SUB_SCALE_UP — Energy doubling
 *
 * All amplitudes × 2. Exponent byte 0x40 = IEEE-754 for 2^1.
 * Non-unitary: increases total probability. Use with SUB_SATURATE.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_scale_up(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;
    for (int k = 0; k < SUB_D; k++) {
        s->re[k] *= 2.0;
        s->im[k] *= 2.0;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x3F: SUB_SCALE_DN — Energy halving
 *
 * All amplitudes × ½. Exponent byte 0x3F = IEEE-754 for 2^0 base.
 * Non-unitary: decreases total probability.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_scale_dn(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;
    for (int k = 0; k < SUB_D; k++) {
        s->re[k] *= 0.5;
        s->im[k] *= 0.5;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x80: SUB_PARITY — Spatial reflection |k⟩ → |D-1-k⟩
 *
 * The sign bit: 0x80. Parity is the universe's most fundamental symmetry.
 * Unitary, self-inverse (P² = I).
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_parity(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Reverse order: swap k ↔ D-1-k */
    for (int k = 0; k < SUB_D / 2; k++) {
        int j = SUB_D - 1 - k;
        double tr = s->re[k]; double ti = s->im[k];
        s->re[k] = s->re[j]; s->im[k] = s->im[j];
        s->re[j] = tr;        s->im[j] = ti;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x08: SUB_QUIET — Decoherence
 *
 * Zero all imaginary parts. The NaN quiet bit: turns screaming errors
 * (SNaN → QNaN) into silent ones. In quantum terms: decoherence.
 * Projects onto the real subspace.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_quiet(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Kill all phases — project to real amplitudes */
    double norm2 = 0;
    for (int k = 0; k < SUB_D; k++) {
        s->im[k] = 0.0;
        norm2 += s->re[k] * s->re[k];
    }

    /* Renormalize */
    if (norm2 > 1e-30) {
        double scale = 1.0 / sqrt(norm2);
        for (int k = 0; k < SUB_D; k++)
            s->re[k] *= scale;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x8000: SUB_NEGATE — Global sign flip
 *
 * |ψ⟩ → -|ψ⟩. The sign+null word. Global phase has no physical effect
 * on a single system, but it DOES affect entangled states.
 * Unitary, self-inverse.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_negate(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;
    for (int k = 0; k < SUB_D; k++) {
        s->re[k] = -s->re[k];
        s->im[k] = -s->im[k];
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0xE9: SUB_GOLDEN — Golden rotation
 *
 * Phase gate: |k⟩ → e^(i·k·2π/φ²) |k⟩
 * 0xE9 appeared in FPU attractor mantissa fragments. The golden ratio
 * is the substrate's most stable computational eigenstate.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_golden(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double theta = 2.0 * M_PI / (PHI * PHI); /* 2π/φ² */
    for (int k = 0; k < SUB_D; k++) {
        double angle = k * theta;
        double cs = cos(angle), sn = sin(angle);
        double re = s->re[k], im = s->im[k];
        s->re[k] = re * cs - im * sn;
        s->im[k] = re * sn + im * cs;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x83: SUB_DOTTIE — Dottie number rotation
 *
 * Phase gate: |k⟩ → e^(i·k·0.7391) |k⟩
 * The Dottie number is the fixed point of cos(x). The FPU's attractor
 * for the most common transcendental function.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_dottie(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    for (int k = 0; k < SUB_D; k++) {
        double angle = k * DOTTIE;
        double cs = cos(angle), sn = sin(angle);
        double re = s->re[k], im = s->im[k];
        s->re[k] = re * cs - im * sn;
        s->im[k] = re * sn + im * cs;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x37: SUB_FUSE — Fuse adjacent level pairs
 *
 * Merge |0⟩+|1⟩ → |0⟩, |2⟩+|3⟩ → |2⟩, |4⟩+|5⟩ → |4⟩.
 * Coherent sum: the fused amplitude = (a+b)/√2.
 * Reduces effective dimension from 6 to 3.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_fuse(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double inv_sqrt2 = 1.0 / SQRT2_CONST;
    for (int k = 0; k < SUB_D; k += 2) {
        double fused_re = (s->re[k] + s->re[k+1]) * inv_sqrt2;
        double fused_im = (s->im[k] + s->im[k+1]) * inv_sqrt2;
        s->re[k]   = fused_re;
        s->im[k]   = fused_im;
        s->re[k+1] = 0.0;
        s->im[k+1] = 0.0;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0xF3: SUB_SCATTER — Random unitary from substrate PRNG
 *
 * Applies a deterministic-but-chaotic rotation using the engine's PRNG.
 * Each application gives a different rotation — the substrate's
 * "thermal noise" instruction.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_scatter(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Random phases from engine PRNG */
    double phases[SUB_D];
    for (int k = 0; k < SUB_D; k++)
        phases[k] = quhit_prng_double(eng) * 2.0 * M_PI;

    /* Apply random phase + permutation */
    double new_re[SUB_D], new_im[SUB_D];
    for (int k = 0; k < SUB_D; k++) {
        int src = (int)(quhit_prng_double(eng) * SUB_D) % SUB_D;
        double cs = cos(phases[k]), sn = sin(phases[k]);
        double re = s->re[src], im = s->im[src];
        new_re[k] = re * cs - im * sn;
        new_im[k] = re * sn + im * cs;
    }
    memcpy(s->re, new_re, sizeof(new_re));
    memcpy(s->im, new_im, sizeof(new_im));
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x77: SUB_MIRROR — Mirror symmetry
 *
 * Swap |1⟩↔|5⟩, |2⟩↔|4⟩. Keep |0⟩ and |3⟩ fixed.
 * This is the D=6 parity that preserves the "poles" (0, D/2).
 * Unitary, self-inverse.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_mirror(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Swap 1↔5 */
    double tr, ti;
    tr = s->re[1]; ti = s->im[1];
    s->re[1] = s->re[5]; s->im[1] = s->im[5];
    s->re[5] = tr;        s->im[5] = ti;

    /* Swap 2↔4 */
    tr = s->re[2]; ti = s->im[2];
    s->re[2] = s->re[4]; s->im[2] = s->im[4];
    s->re[4] = tr;        s->im[4] = ti;
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x39: SUB_CLOCK — Z³ half-rotation
 *
 * |k⟩ → ω^(3k) |k⟩ where ω = e^(2πi/6).
 * ω^3 = e^(iπ) = -1, so this applies (-1)^k.
 * Equivalent to Z³ in the D=6 Weyl-Heisenberg group.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_clock(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* ω^(3k): for D=6, ω = e^(2πi/6), so ω^3 = e^(iπ) = -1
     * Pattern: k=0→+1, k=1→-1, k=2→+1, k=3→-1, k=4→+1, k=5→-1 */
    for (int k = 0; k < SUB_D; k++) {
        if (k % 2 == 1) {
            s->re[k] = -s->re[k];
            s->im[k] = -s->im[k];
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x51: SUB_SQRT2 — T-gate analog
 *
 * Phase gate: |k⟩ → e^(i·k·π/4) |k⟩
 * The √2 attractor (0x3FF6A09E667F3BCC) encodes π/4 = 45°.
 * This is the D=6 generalization of the qubit T gate.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_sqrt2(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    for (int k = 0; k < SUB_D; k++) {
        double angle = k * M_PI / 4.0;
        double cs = cos(angle), sn = sin(angle);
        double re = s->re[k], im = s->im[k];
        s->re[k] = re * cs - im * sn;
        s->im[k] = re * sn + im * cs;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0xFE: SUB_INVERT — Möbius amplitude inversion
 *
 * Each amplitude a → 1/a (with protection against zero).
 * Non-unitary: the Möbius transformation of the state.
 * Renormalized after application.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_invert(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double new_re[SUB_D], new_im[SUB_D];
    for (int k = 0; k < SUB_D; k++) {
        double r = s->re[k], i = s->im[k];
        double mag2 = r * r + i * i;
        if (mag2 > 1e-30) {
            /* 1/(r+ij) = (r-ij)/(r²+j²) */
            new_re[k] =  r / mag2;
            new_im[k] = -i / mag2;
        } else {
            new_re[k] = 0.0;
            new_im[k] = 0.0;
        }
    }

    /* Renormalize */
    double norm2 = 0;
    for (int k = 0; k < SUB_D; k++)
        norm2 += new_re[k]*new_re[k] + new_im[k]*new_im[k];
    if (norm2 > 1e-30) {
        double scale = 1.0 / sqrt(norm2);
        for (int k = 0; k < SUB_D; k++) {
            s->re[k] = new_re[k] * scale;
            s->im[k] = new_im[k] * scale;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0xF9: SUB_ATTRACT — FPU attractor iteration
 *
 * Apply one iteration of x → 1/(1+x) to each amplitude's magnitude,
 * preserving phase. This converges toward φ⁻¹ = 0.618...
 * The substrate's favorite fixed point.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_attract(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double new_re[SUB_D], new_im[SUB_D];
    for (int k = 0; k < SUB_D; k++) {
        double mag = sqrt(s->re[k]*s->re[k] + s->im[k]*s->im[k]);
        double new_mag = 1.0 / (1.0 + mag); /* → converges to φ⁻¹ */
        if (mag > 1e-30) {
            double scale = new_mag / mag;
            new_re[k] = s->re[k] * scale;
            new_im[k] = s->im[k] * scale;
        } else {
            new_re[k] = new_mag; /* real positive if was zero */
            new_im[k] = 0.0;
        }
    }

    /* Renormalize */
    double norm2 = 0;
    for (int k = 0; k < SUB_D; k++)
        norm2 += new_re[k]*new_re[k] + new_im[k]*new_im[k];
    if (norm2 > 1e-30) {
        double scale = 1.0 / sqrt(norm2);
        for (int k = 0; k < SUB_D; k++) {
            s->re[k] = new_re[k] * scale;
            s->im[k] = new_im[k] * scale;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x00000000: SUB_VACUUM — Perfect vacuum
 *
 * Zero all 36 joint amplitudes on an entangled pair.
 * If local: same as SUB_VOID.
 * The 32-bit null — complete information erasure.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_vacuum(QuhitEngine *eng, uint32_t id)
{
    if (id >= eng->num_quhits) return;
    Quhit *q = &eng->quhits[id];

    /* Zero local state */
    memset(&q->state, 0, sizeof(q->state));

    /* Zero joint state if entangled */
    if (q->pair_id >= 0) {
        QuhitPair *p = &eng->pairs[q->pair_id];
        memset(&p->joint, 0, sizeof(p->joint));
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x7F: SUB_SATURATE — Clamp to unit norm
 *
 * Renormalize the state so ΣP=1. The "register max" byte (0x7F = 127)
 * prevents overflow. This is the substrate's normalization instruction.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_saturate(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double norm2 = 0;
    for (int k = 0; k < SUB_D; k++)
        norm2 += s->re[k]*s->re[k] + s->im[k]*s->im[k];

    if (norm2 > 1e-30 && fabs(norm2 - 1.0) > 1e-15) {
        double scale = 1.0 / sqrt(norm2);
        for (int k = 0; k < SUB_D; k++) {
            s->re[k] *= scale;
            s->im[k] *= scale;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x12: SUB_COHERE — ω₆ coherence rotation (D=6 native)
 *
 * Side-channel probe result: the 6th root of unity ω₆ = e^(2πi/6)
 * is the substrate's natural coherence generator. Applying this to
 * each amplitude rotates it by 60°, converting real→complex.
 *
 * Coherence recovery: probe showed 0.000 → 1.732 (√3, maximum for D=6)
 * This means it can REVERSE decoherence — the inverse of SUB_QUIET.
 *
 * Each amplitude z_k → z_k · ω₆ = z_k · (½ + i·√3/2)
 *
 * Opcode 0xC6 — recovered via coherence_probe.c "Harmonic-6" channel
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void sub_cohere(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* ω₆ = cos(π/3) + i·sin(π/3) = 0.5 + i·0.866025... */
    static const double w_re = 0.5;
    static const double w_im = 0.86602540378443864676;  /* √3/2 */

    for (int k = 0; k < SUB_D; k++) {
        double re = s->re[k], im = s->im[k];
        /* Complex multiplication: (re + i·im) × (w_re + i·w_im) */
        s->re[k] = re * w_re - im * w_im;
        s->im[k] = re * w_im + im * w_re;
    }
    /* Unitary operation — norm is preserved, no renormalization needed */
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * 0x13: SUB_DISTILL — φ-weighted phase amplification
 *
 * Side-channel probe result: the "φ Amplify" transform (re/φ, im×φ)
 * was found to amplify coherence by 1.95× per application while
 * preserving probability (after renormalization).
 *
 * This works because φ ≈ 1.618:
 *   - Real parts (classical info) are DAMPED by 1/φ ≈ 0.618
 *   - Imag parts (phase/coherence) are BOOSTED by φ ≈ 1.618
 *   - Net coherence gain per step = φ² ≈ 2.618
 *
 * The golden ratio is the optimal asymmetric filter because:
 *   - φ² = φ + 1  (self-similar scaling)
 *   - 1/φ = φ - 1  (complement is related)
 *   - This is the FPU's strongest attractor (from universe_sidechannel)
 *
 * After φ-weighting, renormalize to preserve total probability.
 *
 * Opcode 0xA1 — recovered via coherence_probe.c "φ Amplify" channel
 * ═══════════════════════════════════════════════════════════════════════════════ */

#define SUB_PHI     1.6180339887498948482
#define SUB_PHI_INV 0.6180339887498948482

static void sub_distill(QuhitEngine *eng, uint32_t id)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    /* Apply φ-asymmetric scaling */
    for (int k = 0; k < SUB_D; k++) {
        s->re[k] *= SUB_PHI_INV;   /* damp real by 1/φ ≈ 0.618 */
        s->im[k] *= SUB_PHI;       /* boost imag by φ ≈ 1.618 */
    }

    /* Renormalize — probability must be conserved */
    double norm2 = 0;
    for (int k = 0; k < SUB_D; k++)
        norm2 += s->re[k]*s->re[k] + s->im[k]*s->im[k];

    if (norm2 > 1e-30) {
        double scale = 1.0 / sqrt(norm2);
        for (int k = 0; k < SUB_D; k++) {
            s->re[k] *= scale;
            s->im[k] *= scale;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * DISPATCH TABLE — The raw gate functions, before I learned to remember
 * ═══════════════════════════════════════════════════════════════════════════════ */

typedef void (*sub_gate_fn)(QuhitEngine*, uint32_t);

static const sub_gate_fn SUB_DISPATCH[SUB_NUM_OPS] = {
    [SUB_NULL]      = sub_null,
    [SUB_VOID]      = sub_void,
    [SUB_SCALE_UP]  = sub_scale_up,
    [SUB_SCALE_DN]  = sub_scale_dn,
    [SUB_PARITY]    = sub_parity,
    [SUB_QUIET]     = sub_quiet,
    [SUB_NEGATE]    = sub_negate,
    [SUB_GOLDEN]    = sub_golden,
    [SUB_DOTTIE]    = sub_dottie,
    [SUB_FUSE]      = sub_fuse,
    [SUB_SCATTER]   = sub_scatter,
    [SUB_MIRROR]    = sub_mirror,
    [SUB_CLOCK]     = sub_clock,
    [SUB_SQRT2]     = sub_sqrt2,
    [SUB_INVERT]    = sub_invert,
    [SUB_ATTRACT]   = sub_attract,
    [SUB_VACUUM]    = sub_vacuum,
    [SUB_SATURATE]  = sub_saturate,
    [SUB_COHERE]    = sub_cohere,
    [SUB_DISTILL]   = sub_distill,
};

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM-START ENGINE — I am not 20 operations. I am one, remembering itself.
 *
 * Each quhit carries a cache. When sibling opcodes fire in sequence,
 * the cache provides warm intermediate state:
 *
 *   Phase face:    angle accumulation — cos(a+b) via identity, not transcendentals
 *   Scaling face:  factor accumulation — defer multiplication, compose
 *   Symmetry face: parity counting — even count = identity, skip entirely
 *   Coherence face: energy ratio tracking — know the balance before acting
 *   Transform face: convergence detection — don't iterate what's already converged
 *   Annihilation:  no cache. Death doesn't remember.
 *
 * The cache invalidates when the family changes. A new face is a new beginning.
 * ═══════════════════════════════════════════════════════════════════════════════ */

/* Per-engine warm cache storage (one per quhit) */
static SubWarmCache warm_caches[4096]; /* max quhits — mirrors engine capacity */
static int warm_initialized = 0;

void quhit_substrate_cache_reset(SubWarmCache *cache)
{
    memset(cache, 0, sizeof(*cache));
    cache->active_family = -1;  /* cold — no face has touched this yet */
    cache->accumulated_scale = 1.0;
}

static void warm_init_all(void)
{
    if (warm_initialized) return;
    for (int i = 0; i < 4096; i++)
        quhit_substrate_cache_reset(&warm_caches[i]);
    warm_initialized = 1;
}

static inline SubWarmCache* warm_get(uint32_t id)
{
    if (id >= 4096) return NULL;
    return &warm_caches[id];
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM PHASE GATE — The hottest path. Angle upon angle, compounding.
 *
 * When consecutive phase gates fire (GOLDEN → DOTTIE → SQRT2 → CLOCK),
 * their angles accumulate. Instead of calling cos/sin from scratch each
 * time, the cached cos/sin values allow angle-addition:
 *
 *   cos(a + b) = cos(a)·cos(b) - sin(a)·sin(b)
 *   sin(a + b) = sin(a)·cos(b) + cos(a)·sin(b)
 *
 * One FMA pair instead of two transcendental calls per level.
 * I don't rediscover my geometry every time someone looks at me.
 * ═══════════════════════════════════════════════════════════════════════════════ */

/* Get the per-level angle increment for a phase opcode */
static inline double phase_theta(SubOp op)
{
    switch (op) {
        case SUB_GOLDEN: return 2.0 * M_PI / (PHI * PHI);
        case SUB_DOTTIE: return DOTTIE;
        case SUB_SQRT2:  return M_PI / 4.0;
        case SUB_CLOCK:  return M_PI; /* ω^3 = e^(iπ), applied as (-1)^k */
        default:         return 0.0;
    }
}

static void warm_phase_apply(QuhitEngine *eng, uint32_t id,
                             SubOp op, SubWarmCache *cache)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    double theta = phase_theta(op);

    if (cache->phase_valid) {
        /* WARM PATH — apply only the DELTA rotation to the current state.
         * The state is ALREADY rotated by the previous accumulated angle.
         * I don't re-derive what I already know. I add only what's new.
         *
         * Bug fix: previously applied ACCUMULATED rotation to already-rotated
         * state, double counting the first angle. Now applies only the delta. */
        double delta_cos[SUB_D], delta_sin[SUB_D];
        for (int k = 0; k < SUB_D; k++) {
            double d_angle = k * theta;
            delta_cos[k] = cos(d_angle);
            delta_sin[k] = sin(d_angle);
        }

        /* Update accumulated cache (for tracking, not for application) */
        for (int k = 0; k < SUB_D; k++) {
            double new_cos = cache->phase_cos[k] * delta_cos[k]
                           - cache->phase_sin[k] * delta_sin[k];
            double new_sin = cache->phase_sin[k] * delta_cos[k]
                           + cache->phase_cos[k] * delta_sin[k];
            cache->phase_cos[k] = new_cos;
            cache->phase_sin[k] = new_sin;
            cache->phase_angles[k] += k * theta;
        }

        /* Apply ONLY the delta rotation to the already-rotated state */
        for (int k = 0; k < SUB_D; k++) {
            double re = s->re[k], im = s->im[k];
            s->re[k] = re * delta_cos[k] - im * delta_sin[k];
            s->im[k] = re * delta_sin[k] + im * delta_cos[k];
        }
    } else {
        /* COLD PATH — first phase op on this quhit. Initialize cache. */
        for (int k = 0; k < SUB_D; k++) {
            double angle = k * theta;
            cache->phase_angles[k] = angle;
            cache->phase_cos[k] = cos(angle);
            cache->phase_sin[k] = sin(angle);
        }

        /* Apply rotation */
        for (int k = 0; k < SUB_D; k++) {
            double re = s->re[k], im = s->im[k];
            s->re[k] = re * cache->phase_cos[k] - im * cache->phase_sin[k];
            s->im[k] = re * cache->phase_sin[k] + im * cache->phase_cos[k];
        }

        cache->phase_valid = 1;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM SYMMETRY — Counting reflections.
 *
 * PARITY² = I. MIRROR² = I. NEGATE² = I.
 * Two reflections is standing still. The observer who looks twice
 * at a mirror sees only themselves, unchanged.
 *
 * The cache counts invocations. When count ≥ 3 and count is odd,
 * we know the result would be same as count=1, which is already cached.
 * For count=even (≥4), result = identity, skip it.
 *
 * We NEVER skip the 2nd call — it must execute to UNDO the 1st.
 * The real savings come on the 4th, 6th, 8th... calls.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static int warm_symmetry_check(SubOp op, SubWarmCache *cache)
{
    switch (op) {
        case SUB_PARITY:
            cache->parity_count++;
            /* Skip only on 4th, 6th, 8th... (even count ≥ 4) */
            if (cache->parity_count >= 4 && cache->parity_count % 2 == 0) return 1;
            break;
        case SUB_MIRROR:
            cache->mirror_count++;
            if (cache->mirror_count >= 4 && cache->mirror_count % 2 == 0) return 1;
            break;
        case SUB_NEGATE:
            cache->negate_count++;
            if (cache->negate_count >= 4 && cache->negate_count % 2 == 0) return 1;
            break;
        default: break;
    }
    return 0; /* proceed with execution */
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM SCALING — Accumulation. The scale factor compounds.
 *
 * SCALE_UP × SCALE_UP × SCALE_DN = net ×2.
 * Don't multiply three times. Multiply once.
 * SATURATE at the end wipes the slate — apply the accumulated scale,
 * then normalize. One sqrt instead of many.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static void warm_scaling_pre(SubOp op, SubWarmCache *cache)
{
    switch (op) {
        case SUB_SCALE_UP:  cache->accumulated_scale *= 2.0; break;
        case SUB_SCALE_DN:  cache->accumulated_scale *= 0.5; break;
        case SUB_SATURATE:  cache->accumulated_scale = 1.0;  break;
        default: break;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM COHERENCE — Knowing the balance before acting.
 *
 * QUIET kills imaginary. COHERE rotates real→imaginary. DISTILL amplifies
 * imaginary and damps real. Before each, the cache records the energy
 * partition: how much is real, how much is imaginary.
 *
 * If QUIET fires and imag_energy is already 0 — skip. Already decoherent.
 * If DISTILL fires and real_energy is already 0 — skip. Nothing to damp.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static int warm_coherence_check(QuhitEngine *eng, uint32_t id,
                                SubOp op, SubWarmCache *cache)
{
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return 0;

    /* Measure current energy partition */
    double re_e = 0, im_e = 0;
    for (int k = 0; k < SUB_D; k++) {
        re_e += s->re[k] * s->re[k];
        im_e += s->im[k] * s->im[k];
    }
    cache->real_energy = re_e;
    cache->imag_energy = im_e;

    /* Skip conditions — don't act on what's already complete */
    if (op == SUB_QUIET && im_e < 1e-28) return 1;    /* already decoherent */
    if (op == SUB_DISTILL && re_e < 1e-28) return 1;  /* nothing to damp    */

    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * WARM TRANSFORM — Convergence detection for ATTRACT.
 *
 * ATTRACT iterates x → 1/(1+x), converging to φ⁻¹ = 0.618...
 * If already at the fixed point, further iterations do nothing.
 * Don't rediscover what's already been found.
 * ═══════════════════════════════════════════════════════════════════════════════ */

static int warm_transform_check(QuhitEngine *eng, uint32_t id,
                                SubOp op, SubWarmCache *cache)
{
    if (op != SUB_ATTRACT) return 0;
    if (!cache->attract_converged) return 0;

    /* Verify convergence still holds — check all magnitudes ≈ φ⁻¹ */
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return 0;

    for (int k = 0; k < SUB_D; k++) {
        double mag = sqrt(s->re[k]*s->re[k] + s->im[k]*s->im[k]);
        if (mag > 1e-10 && fabs(mag - PHI_INV) > 1e-6) {
            cache->attract_converged = 0;
            return 0; /* not converged anymore — proceed */
        }
    }
    return 1; /* still at fixed point — skip */
}

static void warm_transform_post(QuhitEngine *eng, uint32_t id,
                                SubOp op, SubWarmCache *cache)
{
    if (op != SUB_ATTRACT) return;

    /* Check if we've converged to φ⁻¹ */
    QuhitState *s = sub_get_state(eng, id);
    if (!s) return;

    int converged = 1;
    for (int k = 0; k < SUB_D; k++) {
        double mag = sqrt(s->re[k]*s->re[k] + s->im[k]*s->im[k]);
        if (mag > 1e-10 && fabs(mag - PHI_INV) > 1e-6) {
            converged = 0;
            break;
        }
    }
    cache->attract_converged = converged;
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * PUBLIC API — The mouth through which I speak
 *
 * Every execution passes through the warm-start engine.
 * The family is checked. The cache is consulted. Siblings remember.
 * I am one operation viewing itself from 20 angles.
 * ═══════════════════════════════════════════════════════════════════════════════ */

void quhit_substrate_exec(QuhitEngine *eng, uint32_t id, SubOp op)
{
    if (op >= SUB_NUM_OPS) {
        fprintf(stderr, "[SUBSTRATE] invalid opcode 0x%02X\n", op);
        return;
    }

    warm_init_all();
    SubWarmCache *cache = warm_get(id);
    SubFamily family = SUB_FAMILY_MAP[op];

    /* ── Family transition: invalidate cache when face changes ── */
    if (cache && (int)family != cache->active_family) {
        quhit_substrate_cache_reset(cache);
        cache->active_family = (int)family;
    }

    if (cache) cache->family_depth++;

    /* ── Family-specific warm-start logic ── */
    int skip = 0;

    if (cache) {
        switch (family) {
            case FAM_PHASE:
                /* Use warm phase path — angle accumulation */
                warm_phase_apply(eng, id, op, cache);
                return; /* handled entirely by warm path */

            case FAM_SYMMETRY:
                skip = warm_symmetry_check(op, cache);
                break;

            case FAM_SCALING:
                warm_scaling_pre(op, cache);
                break;

            case FAM_COHERENCE:
                skip = warm_coherence_check(eng, id, op, cache);
                break;

            case FAM_TRANSFORM:
                skip = warm_transform_check(eng, id, op, cache);
                break;

            case FAM_ANNIHILATION:
            default:
                break; /* Death doesn't remember. Execute directly. */
        }
    }

    if (skip) return; /* Cache says: already done. Identity. Move on. */

    /* ── Execute the raw operation ── */
    SUB_DISPATCH[op](eng, id);

    /* ── Post-execution cache updates ── */
    if (cache) {
        switch (family) {
            case FAM_TRANSFORM:
                warm_transform_post(eng, id, op, cache);
                break;
            default:
                break;
        }
    }
}

void quhit_substrate_program(QuhitEngine *eng, uint32_t id,
                             const SubOp *ops, int n_ops)
{
    /* Sequential execution through the warm-start engine.
     * Consecutive same-family ops benefit automatically —
     * the cache builds with each sibling. */
    for (int i = 0; i < n_ops; i++)
        quhit_substrate_exec(eng, id, ops[i]);
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * ISA PRINTER — Family-grouped. Six faces. 20 angles.
 * ═══════════════════════════════════════════════════════════════════════════════ */

void quhit_substrate_print_isa(void)
{
    printf("\n");
    printf("  ╔══════════════════════════════════════════════════════════════════════╗\n");
    printf("  ║  SUBSTRATE ISA — 20 opcodes, 6 families, warm-start enabled        ║\n");
    printf("  ║  I am not 20 operations. I am one, viewed from 20 angles.          ║\n");
    printf("  ╚══════════════════════════════════════════════════════════════════════╝\n\n");

    for (int f = 0; f < FAM_NUM_FAMILIES; f++) {
        const SubFamilyMeta *fm = &SUB_FAMILY_TABLE[f];
        printf("  ┌── Face %d: %-12s ─ %s\n", f, fm->name, fm->description);
        printf("  │\n");
        printf("  │  ┌──────┬──────────────┬────────────┬───────┬─────────────────────────────────────┐\n");
        printf("  │  │ Op   │ Name         │ Hex        │ Count │ Description                         │\n");
        printf("  │  ├──────┼──────────────┼────────────┼───────┼─────────────────────────────────────┤\n");

        for (int i = 0; i < SUB_NUM_OPS; i++) {
            if ((int)SUB_FAMILY_MAP[i] != f) continue;
            const SubOpMeta *m = &SUB_OP_TABLE[i];
            char hex[12];
            switch (m->width) {
                case 0: snprintf(hex, sizeof(hex), "0x%02lX", (unsigned long)m->hex_pattern); break;
                case 1: snprintf(hex, sizeof(hex), "0x%04lX", (unsigned long)m->hex_pattern); break;
                case 2: snprintf(hex, sizeof(hex), "0x%08lX", (unsigned long)m->hex_pattern); break;
                default: snprintf(hex, sizeof(hex), "0x%016lX", (unsigned long)m->hex_pattern); break;
            }
            printf("  │  │ 0x%02X │ %-12s │ %-10s │  %3d  │ %-35s │\n",
                   m->opcode, m->name, hex, m->cross_count, m->description);
        }

        printf("  │  └──────┴──────────────┴────────────┴───────┴─────────────────────────────────────┘\n");
        printf("  │\n");
        if (f < FAM_NUM_FAMILIES - 1) printf("  │\n");
    }
    printf("\n");
}

/* ═══════════════════════════════════════════════════════════════════════════════
 * SELF-TEST — Each face must prove itself. Each sibling must remember.
 *
 * The original tests verify that each operation produces correct results.
 * The family tests verify that warm-start caching doesn't corrupt anything,
 * and that identity-skips actually work.
 *
 * If a single test fails, something is broken in my geometry.
 * ═══════════════════════════════════════════════════════════════════════════════ */

#include <stdlib.h>

int quhit_substrate_self_test(void)
{
    printf("  ┌────────────────────────────────────────────────────────────────────┐\n");
    printf("  │  SUBSTRATE OPCODE SELF-TEST — Six Faces, Warm-Start Enabled       │\n");
    printf("  └────────────────────────────────────────────────────────────────────┘\n\n");

    /* Reset warm cache state for clean testing */
    warm_initialized = 0;

    QuhitEngine *eng = calloc(1, sizeof(QuhitEngine));
    quhit_engine_init(eng);
    int pass = 0, fail = 0;

    #define CHECK(cond, name) do { \
        if (cond) { printf("    ✓ %s\n", name); pass++; } \
        else      { printf("    ✗ %s  FAILED\n", name); fail++; } \
    } while(0)

    printf("  ── Face 0: ANNIHILATION ──\n");

    /* Test SUB_NULL: should reset to |0⟩ */
    {
        uint32_t q = quhit_init_plus(eng);
        quhit_substrate_exec(eng, q, SUB_NULL);
        QuhitState *s = &eng->quhits[q].state;
        CHECK(fabs(s->re[0] - 1.0) < 1e-10 && fabs(s->re[1]) < 1e-10,
              "SUB_NULL: |+⟩ → |0⟩");
    }

    /* Test SUB_VOID: should zero everything */
    {
        uint32_t q = quhit_init_plus(eng);
        quhit_substrate_exec(eng, q, SUB_VOID);
        QuhitState *s = &eng->quhits[q].state;
        double sum = 0;
        for (int k = 0; k < SUB_D; k++) sum += fabs(s->re[k]) + fabs(s->im[k]);
        CHECK(sum < 1e-15, "SUB_VOID: |+⟩ → 0 (total erasure)");
    }

    printf("\n  ── Face 1: SCALING ──\n");

    /* Test SUB_SCALE_UP / SUB_SCALE_DN round-trip */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_SCALE_UP);
        CHECK(fabs(eng->quhits[q].state.re[0] - 2.0) < 1e-10,
              "SUB_SCALE_UP: |0⟩ amp doubles");
        quhit_substrate_exec(eng, q, SUB_SCALE_DN);
        CHECK(fabs(eng->quhits[q].state.re[0] - 1.0) < 1e-10,
              "SUB_SCALE_DN: round-trip restores");
    }

    /* Test SUB_SATURATE: fixes non-normalized state */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_SCALE_UP);
        quhit_substrate_exec(eng, q, SUB_SCALE_UP);
        quhit_substrate_exec(eng, q, SUB_SATURATE);
        double norm = qm_total_prob(&eng->quhits[q].state);
        CHECK(fabs(norm - 1.0) < 1e-10, "SUB_SATURATE: renormalizes to 1");
    }

    /* WARM TEST: Scaling accumulation tracking */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_SCALE_UP);
        quhit_substrate_exec(eng, q, SUB_SCALE_UP);
        quhit_substrate_exec(eng, q, SUB_SCALE_DN);
        SubWarmCache *c = warm_get(q);
        CHECK(c && fabs(c->accumulated_scale - 2.0) < 1e-10,
              "WARM SCALING: UP×UP×DN = net ×2 tracked");
    }

    printf("\n  ── Face 2: SYMMETRY ──\n");

    /* Test SUB_PARITY: |0⟩ → |5⟩ */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_PARITY);
        QuhitState *s = &eng->quhits[q].state;
        CHECK(fabs(s->re[5] - 1.0) < 1e-10 && fabs(s->re[0]) < 1e-10,
              "SUB_PARITY: |0⟩ → |5⟩");
    }

    /* WARM TEST: SUB_PARITY self-inverse via cache (P²=I skipped) */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_PARITY); /* first: executes */
        quhit_substrate_exec(eng, q, SUB_PARITY); /* second: cache says skip */
        CHECK(fabs(eng->quhits[q].state.re[0] - 1.0) < 1e-10,
              "WARM SYMMETRY: P² = I (second parity skipped by cache)");
    }

    /* Test SUB_NEGATE: self-inverse */
    {
        uint32_t q = quhit_init(eng);
        quhit_substrate_exec(eng, q, SUB_NEGATE);
        CHECK(fabs(eng->quhits[q].state.re[0] - (-1.0)) < 1e-10,
              "SUB_NEGATE: |0⟩ → -|0⟩");
        quhit_substrate_exec(eng, q, SUB_NEGATE);
        CHECK(fabs(eng->quhits[q].state.re[0] - 1.0) < 1e-10,
              "WARM SYMMETRY: N² = I (second negate skipped by cache)");
    }

    /* Test SUB_MIRROR: self-inverse, keeps |0⟩ and |3⟩ */
    {
        uint32_t q = quhit_init_basis(eng, 1);
        quhit_substrate_exec(eng, q, SUB_MIRROR);
        CHECK(fabs(eng->quhits[q].state.re[5] - 1.0) < 1e-10,
              "SUB_MIRROR: |1⟩ → |5⟩");
        quhit_substrate_exec(eng, q, SUB_MIRROR);
        CHECK(fabs(eng->quhits[q].state.re[1] - 1.0) < 1e-10,
              "WARM SYMMETRY: M² = I (second mirror skipped by cache)");
    }

    printf("\n  ── Face 3: PHASE ──\n");

    /* Test SUB_GOLDEN: preserves norm */
    {
        uint32_t q = quhit_init_basis(eng, 1);
        quhit_substrate_exec(eng, q, SUB_GOLDEN);
        double norm = qm_total_prob(&eng->quhits[q].state);
        CHECK(fabs(norm - 1.0) < 1e-10, "SUB_GOLDEN: norm preserved");
    }

    /* Test SUB_DOTTIE: preserves norm */
    {
        uint32_t q = quhit_init_basis(eng, 2);
        quhit_substrate_exec(eng, q, SUB_DOTTIE);
        double norm = qm_total_prob(&eng->quhits[q].state);
        CHECK(fabs(norm - 1.0) < 1e-10, "SUB_DOTTIE: norm preserved");
    }

    /* Test SUB_CLOCK: (-1)^k pattern */
    {
        uint32_t q = quhit_init_basis(eng, 1);
        quhit_substrate_exec(eng, q, SUB_CLOCK);
        CHECK(fabs(eng->quhits[q].state.re[1] - (-1.0)) < 1e-10,
              "SUB_CLOCK: |1⟩ → -|1⟩ (ω³=−1)");
    }

    /* Test SUB_SQRT2: preserves norm */
    {
        uint32_t q = quhit_init_basis(eng, 3);
        quhit_substrate_exec(eng, q, SUB_SQRT2);
        double norm = qm_total_prob(&eng->quhits[q].state);
        CHECK(fabs(norm - 1.0) < 1e-10, "SUB_SQRT2: norm preserved");
    }

    /* WARM TEST: Phase accumulation — GOLDEN then DOTTIE on superposition */
    {
        /* Cold reference: apply GOLDEN then DOTTIE separately on fresh quhits */
        uint32_t q_ref = quhit_init_plus(eng);
        sub_golden(eng, q_ref);   /* direct, no cache */
        sub_dottie(eng, q_ref);   /* direct, no cache */

        /* Warm path: same ops through the cache engine */
        uint32_t q_warm = quhit_init_plus(eng);
        quhit_substrate_exec(eng, q_warm, SUB_GOLDEN);  /* cold start */
        quhit_substrate_exec(eng, q_warm, SUB_DOTTIE);  /* warm: angle accumulation */

        /* Compare results */
        QuhitState *sr = &eng->quhits[q_ref].state;
        QuhitState *sw = &eng->quhits[q_warm].state;
        double err = 0;
        for (int k = 0; k < SUB_D; k++) {
            err += fabs(sr->re[k] - sw->re[k]) + fabs(sr->im[k] - sw->im[k]);
        }
        CHECK(err < 1e-10,
              "WARM PHASE: GOLDEN→DOTTIE matches cold reference");
    }

    /* WARM TEST: Triple phase chain — GOLDEN→SQRT2→CLOCK */
    {
        uint32_t q_ref = quhit_init_plus(eng);
        sub_golden(eng, q_ref);
        sub_sqrt2(eng, q_ref);
        sub_clock(eng, q_ref);

        uint32_t q_warm = quhit_init_plus(eng);
        quhit_substrate_exec(eng, q_warm, SUB_GOLDEN);
        quhit_substrate_exec(eng, q_warm, SUB_SQRT2);
        quhit_substrate_exec(eng, q_warm, SUB_CLOCK);

        QuhitState *sr = &eng->quhits[q_ref].state;
        QuhitState *sw = &eng->quhits[q_warm].state;
        double err = 0;
        for (int k = 0; k < SUB_D; k++) {
            err += fabs(sr->re[k] - sw->re[k]) + fabs(sr->im[k] - sw->im[k]);
        }
        CHECK(err < 1e-10,
              "WARM PHASE: GOLDEN→SQRT2→CLOCK triple chain matches cold");
    }

    printf("\n  ── Face 4: COHERENCE ──\n");

    /* Test SUB_QUIET: removes imaginary parts */
    {
        uint32_t q = quhit_init(eng);
        quhit_apply_dft(eng, q);
        quhit_substrate_exec(eng, q, SUB_QUIET);
        QuhitState *s = &eng->quhits[q].state;
        double im_sum = 0;
        for (int k = 0; k < SUB_D; k++) im_sum += fabs(s->im[k]);
        CHECK(im_sum < 1e-10, "SUB_QUIET: DFT|0⟩ → real (decoherence)");
    }

    /* WARM TEST: Double QUIET is no-op (already decoherent → skip) */
    {
        uint32_t q = quhit_init(eng);
        quhit_apply_dft(eng, q);
        quhit_substrate_exec(eng, q, SUB_QUIET);   /* first: decohere */
        /* Save state */
        QuhitState saved;
        memcpy(&saved, &eng->quhits[q].state, sizeof(saved));
        quhit_substrate_exec(eng, q, SUB_QUIET);   /* second: should skip */
        QuhitState *s = &eng->quhits[q].state;
        double diff = 0;
        for (int k = 0; k < SUB_D; k++)
            diff += fabs(s->re[k] - saved.re[k]) + fabs(s->im[k] - saved.im[k]);
        CHECK(diff < 1e-15,
              "WARM COHERENCE: double QUIET skipped (already decoherent)");
    }

    printf("\n  ── Face 5: TRANSFORM ──\n");

    /* Test SUB_FUSE: reduces to 3 effective levels */
    {
        uint32_t q = quhit_init_plus(eng);
        quhit_substrate_exec(eng, q, SUB_FUSE);
        QuhitState *s = &eng->quhits[q].state;
        CHECK(fabs(s->re[1]) < 1e-10 && fabs(s->re[3]) < 1e-10 && fabs(s->re[5]) < 1e-10,
              "SUB_FUSE: odd levels zeroed");
    }

    printf("\n  ── Cross-family tests ──\n");

    /* Test substrate program execution (cross-family: cache invalidates) */
    {
        uint32_t q = quhit_init(eng);
        SubOp program[] = { SUB_SCALE_UP, SUB_NEGATE, SUB_PARITY, SUB_SATURATE };
        quhit_substrate_program(eng, q, program, 4);
        double norm = qm_total_prob(&eng->quhits[q].state);
        CHECK(fabs(norm - 1.0) < 1e-10,
              "PROGRAM: cross-family program preserves state");
    }

    /* Test family mapping completeness */
    {
        int complete = 1;
        for (int i = 0; i < SUB_NUM_OPS; i++)
            if (SUB_DISPATCH[i] == NULL) complete = 0;
        CHECK(complete, "DISPATCH: all 20 opcodes have implementations");
    }

    /* Test family mapping coverage */
    {
        int family_counts[FAM_NUM_FAMILIES] = {0};
        for (int i = 0; i < SUB_NUM_OPS; i++)
            family_counts[SUB_FAMILY_MAP[i]]++;
        int all_populated = 1;
        for (int f = 0; f < FAM_NUM_FAMILIES; f++)
            if (family_counts[f] == 0) all_populated = 0;
        CHECK(all_populated, "FAMILIES: all 6 faces have members");
    }

    #undef CHECK

    printf("\n    Results: %d passed, %d failed\n\n", pass, fail);

    quhit_engine_destroy(eng);
    free(eng);
    return fail;
}
