#ifndef POLAR_LEAF_H
#define POLAR_LEAF_H
#include "sparse_bp.h"

/* Structure to hold sparse 2D Joint Probabilities */
typedef struct {
    int nsp;
    int u[3329];  // Up to q states
    int v[3329];
    double p[3329]; 
    // Wait, the number of non-zero states in a 2D joint distribution is at most 3329 
    // IF it was generated by a deterministic map from TWO independent dimensions?
    // No, if S_e and S_o have nsp_e and nsp_o, the joint has nsp_e * nsp_o states!
    // If nsp_e = 7 and nsp_o = 7, there are 49 states.
    // If it's dense, it's 3329 * 3329 = 10^7 states!
} JointSparse2D;

/* In layer 7, S_e and S_o are INDEPENDENT going down.
 * So the joint distribution is P(S_e=x, S_o=y) = P(S_e=x) P(S_o=y).
 * Since they are independent, we don't even need to store the joint!
 * We can just compute the 1D marginals DIRECTLY without making full 2D arrays!
 */

/*
 * Y_e = A00_e S0_e + Z A00_o S0_o + A01_e S1_e + Z A01_o S1_o
 * Y_o = A00_o S0_e + A00_e S0_o + A01_o S1_e + A01_e S1_o
 */

/* Computes BP message UP to S0_e */
static inline void leaf_k2_s0e(
    const double *in_s0o, const double *in_s1e, const double *in_s1o,
    const double *in_y_e, const double *in_y_o,
    double *out_s0e,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_s0e, 0, 3329 * sizeof(double));
    int sp_s0o[3329], n_s0o=0; for(int i=0;i<3329;i++) if(in_s0o[i]>1e-12) sp_s0o[n_s0o++]=i;
    int sp_s1e[3329], n_s1e=0; for(int i=0;i<3329;i++) if(in_s1e[i]>1e-12) sp_s1e[n_s1e++]=i;
    int sp_s1o[3329], n_s1o=0; for(int i=0;i<3329;i++) if(in_s1o[i]>1e-12) sp_s1o[n_s1o++]=i;

    // We marginalize over S0_o, S1_e, S1_o.
    // That is n_s0o * n_s1e * n_s1o loops!
    // Max 7 * 7 * 7 = 343 loops!
    // Then for each combination, we test all S0_e (length 3329).
    // Total operations = 343 * 3329 = 1.1x10^6 per slot!
    // For 128 slots, this is 1.4x10^8 operations. Extremely fast!
    
    // Precompute constant sums for the S1 part
    for(int i_s1e=0; i_s1e<n_s1e; i_s1e++) {
        int s1e = sp_s1e[i_s1e]; double p_1e = in_s1e[s1e];
        for(int i_s1o=0; i_s1o<n_s1o; i_s1o++) {
            int s1o = sp_s1o[i_s1o]; double p_1o = in_s1o[s1o];
            double p1 = p_1e * p_1o;
            
            int y1_base_e = mod_q(a01_e * s1e + Z * mod_q(a01_o * s1o));
            int y1_base_o = mod_q(a01_o * s1e + a01_e * s1o);
            
            for(int i_s0o=0; i_s0o<n_s0o; i_s0o++) {
                int s0o = sp_s0o[i_s0o]; double p_0o = in_s0o[s0o];
                double p01 = p1 * p_0o;
                
                int y0_base_e = mod_q(y1_base_e + Z * mod_q(a00_o * s0o));
                int y0_base_o = mod_q(y1_base_o + a00_e * s0o);
                
                for(int s0e = 0; s0e < 3329; s0e++) {
                    int ye = mod_q(y0_base_e + a00_e * s0e);
                    double p_ye = in_y_e[ye];
                    if (p_ye < 1e-30) continue;
                    
                    int yo = mod_q(y0_base_o + a00_o * s0e);
                    double p_yo = in_y_o[yo];
                    
                    out_s0e[s0e] += p01 * p_ye * p_yo;
                }
            }
        }
    }
    norm_p_q(out_s0e);
}

// Identical fast nested-loop marginalizations for the other variables
// out_s0o
static inline void leaf_k2_s0o(
    const double *in_s0e, const double *in_s1e, const double *in_s1o,
    const double *in_y_e, const double *in_y_o,
    double *out_s0o,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_s0o, 0, 3329 * sizeof(double));
    int sp_s0e[3329], n_s0e=0; for(int i=0;i<3329;i++) if(in_s0e[i]>1e-12) sp_s0e[n_s0e++]=i;
    int sp_s1e[3329], n_s1e=0; for(int i=0;i<3329;i++) if(in_s1e[i]>1e-12) sp_s1e[n_s1e++]=i;
    int sp_s1o[3329], n_s1o=0; for(int i=0;i<3329;i++) if(in_s1o[i]>1e-12) sp_s1o[n_s1o++]=i;

    for(int i_s1e=0; i_s1e<n_s1e; i_s1e++) {
        int s1e = sp_s1e[i_s1e]; double p_1e = in_s1e[s1e];
        for(int i_s1o=0; i_s1o<n_s1o; i_s1o++) {
            int s1o = sp_s1o[i_s1o]; double p_1o = in_s1o[s1o];
            double p1 = p_1e * p_1o;
            
            int y1_base_e = mod_q(a01_e * s1e + Z * mod_q(a01_o * s1o));
            int y1_base_o = mod_q(a01_o * s1e + a01_e * s1o);
            
            for(int i_s0e=0; i_s0e<n_s0e; i_s0e++) {
                int s0e = sp_s0e[i_s0e]; double p_0e = in_s0e[s0e];
                double p01 = p1 * p_0e;
                
                int y0_base_e = mod_q(y1_base_e + a00_e * s0e);
                int y0_base_o = mod_q(y1_base_o + a00_o * s0e);
                
                for(int s0o = 0; s0o < 3329; s0o++) {
                    int ye = mod_q(y0_base_e + Z * mod_q(a00_o * s0o));
                    double p_ye = in_y_e[ye];
                    if (p_ye < 1e-30) continue;
                    
                    int yo = mod_q(y0_base_o + a00_e * s0o);
                    double p_yo = in_y_o[yo];
                    
                    out_s0o[s0o] += p01 * p_ye * p_yo;
                }
            }
        }
    }
    norm_p_q(out_s0o);
}

// out_s1e
static inline void leaf_k2_s1e(
    const double *in_s0e, const double *in_s0o, const double *in_s1o,
    const double *in_y_e, const double *in_y_o,
    double *out_s1e,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_s1e, 0, 3329 * sizeof(double));
    int sp_s0e[3329], n_s0e=0; for(int i=0;i<3329;i++) if(in_s0e[i]>1e-12) sp_s0e[n_s0e++]=i;
    int sp_s0o[3329], n_s0o=0; for(int i=0;i<3329;i++) if(in_s0o[i]>1e-12) sp_s0o[n_s0o++]=i;
    int sp_s1o[3329], n_s1o=0; for(int i=0;i<3329;i++) if(in_s1o[i]>1e-12) sp_s1o[n_s1o++]=i;

    for(int i_s0e=0; i_s0e<n_s0e; i_s0e++) {
        int s0e = sp_s0e[i_s0e]; double p_0e = in_s0e[s0e];
        for(int i_s0o=0; i_s0o<n_s0o; i_s0o++) {
            int s0o = sp_s0o[i_s0o]; double p_0o = in_s0o[s0o];
            double p0 = p_0e * p_0o;
            
            int y0_base_e = mod_q(a00_e * s0e + Z * mod_q(a00_o * s0o));
            int y0_base_o = mod_q(a00_o * s0e + a00_e * s0o);
            
            for(int i_s1o=0; i_s1o<n_s1o; i_s1o++) {
                int s1o = sp_s1o[i_s1o]; double p_1o = in_s1o[s1o];
                double p01 = p0 * p_1o;
                
                int y1_base_e = mod_q(y0_base_e + Z * mod_q(a01_o * s1o));
                int y1_base_o = mod_q(y0_base_o + a01_e * s1o);
                
                for(int s1e = 0; s1e < 3329; s1e++) {
                    int ye = mod_q(y1_base_e + a01_e * s1e);
                    double p_ye = in_y_e[ye];
                    if (p_ye < 1e-30) continue;
                    
                    int yo = mod_q(y1_base_o + a01_o * s1e);
                    double p_yo = in_y_o[yo];
                    
                    out_s1e[s1e] += p01 * p_ye * p_yo;
                }
            }
        }
    }
    norm_p_q(out_s1e);
}

// out_s1o
static inline void leaf_k2_s1o(
    const double *in_s0e, const double *in_s0o, const double *in_s1e,
    const double *in_y_e, const double *in_y_o,
    double *out_s1o,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_s1o, 0, 3329 * sizeof(double));
    int sp_s0e[3329], n_s0e=0; for(int i=0;i<3329;i++) if(in_s0e[i]>1e-12) sp_s0e[n_s0e++]=i;
    int sp_s0o[3329], n_s0o=0; for(int i=0;i<3329;i++) if(in_s0o[i]>1e-12) sp_s0o[n_s0o++]=i;
    int sp_s1e[3329], n_s1e=0; for(int i=0;i<3329;i++) if(in_s1e[i]>1e-12) sp_s1e[n_s1e++]=i;

    for(int i_s0e=0; i_s0e<n_s0e; i_s0e++) {
        int s0e = sp_s0e[i_s0e]; double p_0e = in_s0e[s0e];
        for(int i_s0o=0; i_s0o<n_s0o; i_s0o++) {
            int s0o = sp_s0o[i_s0o]; double p_0o = in_s0o[s0o];
            double p0 = p_0e * p_0o;
            
            int y0_base_e = mod_q(a00_e * s0e + Z * mod_q(a00_o * s0o));
            int y0_base_o = mod_q(a00_o * s0e + a00_e * s0o);
            
            for(int i_s1e=0; i_s1e<n_s1e; i_s1e++) {
                int s1e = sp_s1e[i_s1e]; double p_1e = in_s1e[s1e];
                double p01 = p0 * p_1e;
                
                int y1_base_e = mod_q(y0_base_e + a01_e * s1e);
                int y1_base_o = mod_q(y0_base_o + a01_o * s1e);
                
                for(int s1o = 0; s1o < 3329; s1o++) {
                    int ye = mod_q(y1_base_e + Z * mod_q(a01_o * s1o));
                    double p_ye = in_y_e[ye];
                    if (p_ye < 1e-30) continue;
                    
                    int yo = mod_q(y1_base_o + a01_e * s1o);
                    double p_yo = in_y_o[yo];
                    
                    out_s1o[s1o] += p01 * p_ye * p_yo;
                }
            }
        }
    }
    norm_p_q(out_s1o);
}

// out_y_e 
static inline void leaf_k2_ye(
    const double *in_s0e, const double *in_s0o, const double *in_s1e, const double *in_s1o,
    const double *in_y_o,
    double *out_ye,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_ye, 0, 3329 * sizeof(double));
    int sp_s0e[3329], n_s0e=0; for(int i=0;i<3329;i++) if(in_s0e[i]>1e-12) sp_s0e[n_s0e++]=i;
    int sp_s0o[3329], n_s0o=0; for(int i=0;i<3329;i++) if(in_s0o[i]>1e-12) sp_s0o[n_s0o++]=i;
    int sp_s1e[3329], n_s1e=0; for(int i=0;i<3329;i++) if(in_s1e[i]>1e-12) sp_s1e[n_s1e++]=i;
    int sp_s1o[3329], n_s1o=0; for(int i=0;i<3329;i++) if(in_s1o[i]>1e-12) sp_s1o[n_s1o++]=i;

    for(int i_s0e=0; i_s0e<n_s0e; i_s0e++) {
        int s0e = sp_s0e[i_s0e]; double p_0e = in_s0e[s0e];
        for(int i_s0o=0; i_s0o<n_s0o; i_s0o++) {
            int s0o = sp_s0o[i_s0o]; double p_0o = in_s0o[s0o];
            for(int i_s1e=0; i_s1e<n_s1e; i_s1e++) {
                int s1e = sp_s1e[i_s1e]; double p_1e = in_s1e[s1e];
                for(int i_s1o=0; i_s1o<n_s1o; i_s1o++) {
                    int s1o = sp_s1o[i_s1o]; double p_1o = in_s1o[s1o];
                    
                    int yo = mod_q(a00_o * s0e + a00_e * s0o + a01_o * s1e + a01_e * s1o);
                    double p_yo = in_y_o[yo];
                    if (p_yo < 1e-30) continue;
                    
                    int ye = mod_q(a00_e * s0e + Z * mod_q(a00_o * s0o) + a01_e * s1e + Z * mod_q(a01_o * s1o));
                    out_ye[ye] += p_0e * p_0o * p_1e * p_1o * p_yo;
                }
            }
        }
    }
    norm_p_q(out_ye);
}

// out_y_o 
static inline void leaf_k2_yo(
    const double *in_s0e, const double *in_s0o, const double *in_s1e, const double *in_s1o,
    const double *in_y_e,
    double *out_yo,
    int a00_e, int a00_o, int a01_e, int a01_o, int Z)
{
    memset(out_yo, 0, 3329 * sizeof(double));
    int sp_s0e[3329], n_s0e=0; for(int i=0;i<3329;i++) if(in_s0e[i]>1e-12) sp_s0e[n_s0e++]=i;
    int sp_s0o[3329], n_s0o=0; for(int i=0;i<3329;i++) if(in_s0o[i]>1e-12) sp_s0o[n_s0o++]=i;
    int sp_s1e[3329], n_s1e=0; for(int i=0;i<3329;i++) if(in_s1e[i]>1e-12) sp_s1e[n_s1e++]=i;
    int sp_s1o[3329], n_s1o=0; for(int i=0;i<3329;i++) if(in_s1o[i]>1e-12) sp_s1o[n_s1o++]=i;

    for(int i_s0e=0; i_s0e<n_s0e; i_s0e++) {
        int s0e = sp_s0e[i_s0e]; double p_0e = in_s0e[s0e];
        for(int i_s0o=0; i_s0o<n_s0o; i_s0o++) {
            int s0o = sp_s0o[i_s0o]; double p_0o = in_s0o[s0o];
            for(int i_s1e=0; i_s1e<n_s1e; i_s1e++) {
                int s1e = sp_s1e[i_s1e]; double p_1e = in_s1e[s1e];
                for(int i_s1o=0; i_s1o<n_s1o; i_s1o++) {
                    int s1o = sp_s1o[i_s1o]; double p_1o = in_s1o[s1o];
                    
                    int ye = mod_q(a00_e * s0e + Z * mod_q(a00_o * s0o) + a01_e * s1e + Z * mod_q(a01_o * s1o));
                    double p_ye = in_y_e[ye];
                    if (p_ye < 1e-30) continue;
                    
                    int yo = mod_q(a00_o * s0e + a00_e * s0o + a01_o * s1e + a01_e * s1o);
                    out_yo[yo] += p_0e * p_0o * p_1e * p_1o * p_ye;
                }
            }
        }
    }
    norm_p_q(out_yo);
}


#endif
